---
name: Alberson
surname: Miranda
position: "Data Scientist | R Developer | Economist | Mathematician"
address: "Vitória, Brazil"
www: "datamares.netlify.app/"
email: "albersonmiranda@hotmail.com"
github: albersonmiranda
linkedin: albersonmiranda
headcolor: "414141"
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Industry Positions

```{r industry}
tribble(
  ~role, ~company, ~loc, ~dates, ~details,
  "Advisor (Credit Risk Modeling Office)", "Bank of the State of Espírito Santo", "Vitória, Brazil", "Jul. 2024 - Present",
  c(
    "Develop, monitor, and fine-tune expected credit loss models (IFRS9) using statistical and machine learning techniques.",
    "Stack: R, Python, Google Cloud Platform, MS SQL Server, VSCode, Jira, Bitbucket."
  ),
  "Advisor (Credit Innovation Office)", "Bank of the State of Espírito Santo", "Vitória, Brazil", "Jan. 2020 - Jun. 2024",
  c(
    "Trained, evaluated, and interpreted statistical models to support data-driven decision-making.",
    "Designed customer segmentation models to support the launch of a new credit card, and formulated pricing equations for service fees and loyalty incentives.",
    "Contributed to the implementation of the company’s first enterprise data warehouse, enabling centralized and scalable data analytics"
  ),
  "Head of Collection", "Bank of the State of Espírito Santo", "Vitória, Brazil", "Apr. 2014 - Dec. 2019",
  c(
    "Developed and implemented collection strategies that improved recovery rates by 12% annually.",
    "Applied econometric techniques for optimized collection and budget planning.",
    "Designed and maintained a MySQL database tailored to collection operations.",
    "Introduced the R programming language to the company, enhancing data analysis capabilities."
  ),
  "Credit Analyst", "Bank of the State of Espírito Santo", "Vitória, Brazil", "Jul. 2008 - Mar. 2014", NULL
) %>%
  detailed_entries(role, dates, company, loc, details)
```

# Education

```{r education}
tribble(
  ~degree, ~uni, ~loc, ~dates, ~details,
  "PhD in Economics", "Universidade Federal do Espírito Santo", "Vitória, Brazil", "Jan. 2024 - Dec. 2027", "Thesis: \"Essays in Hierarchical Time Series\".",
  "M.Sc in Economics", "Universidade Federal do Espírito Santo", "Vitória, Brazil", "Jan. 2022 - Dec. 2023", "Thesis: \"Machine Learning Methods for Optimal Reconciliation of Hierarchical and Grouped Time Series.\"",
  "B.Sc in Mathematics", "Instituto Federal do Espírito Santo", "Vitória, Brazil", "Feb. 2018 - Dec. 2023", NULL,
  "B.Sc in Economics", "Universidade Federal do Espírito Santo", "Vitória, Brazil", "Feb. 2007 - Dec. 2013", NULL
) %>%
  detailed_entries(degree, dates, uni, loc, details)
```

# Open Source

```{r open source}
tribble(
  ~role, ~software, ~what, ~details,
  "Author/Maintainer", "fio", "R Package", "A Rust-powered R package designed for lightning fast economic input-output analysis (https://albersonmiranda.github.io/fio/). ",
  "Core Contributor", "rextendr", "R Package", "An R package that helps scaffolding extendr-enabled packages or compiling Rust code dynamically (https://extendr.github.io/rextendr/).",
  "Author/Maintainer", "R Tools PPA", "Linux Repository", "A PPA for distributing the latest versions of RStudio, Quarto, and Positron for Linux users (both .deb and .rpm) (https://albersonmiranda.github.io/r_tools_ppa/)."
) %>%
  detailed_entries(role, NA, software, what, details)
```

# Projects

```{r projects}
tribble(
  ~role, ~project, ~what, ~details,
  "Translator", "R for Data Science", "Book", "Translator of the portuguese version of the book \"R for Data Science\" by Hadley Wickham and Garrett Grolemund (https://pt.r4ds.hadley.nz/).",
  "Author", "GBIF Biodiversity", "Shiny web app", "A Docker image containing a Shiny app for visualizing global biodiversity data (https://albersonmiranda.shinyapps.io/Global_Biodiversity/)."
) %>%
  detailed_entries(role, NA, project, what, details)
```
