on:
  push:
    branches: [main, master]

name: Update CV

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            - any::vitae

      - name: Render CV
        run: |
          rmarkdown::render('cv.Rmd')
        shell: Rscript {0}

      - name: Upload CV
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf