on:
  push:
    branches: [main, master]

name: Update CV

permissions: read-all

jobs:
  Update-CV:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          install.packages(c("rmarkdown", "vitae"))
        shell: Rscript {0}

      - name: Render CV
        run: |
          rmarkdown::render('vitae/cv/cv.Rmd')
        shell: Rscript {0}

      - name: Upload CV
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf